In [1]:
import numpy as np
import pandas as pd

data = pd.read_csv("C:/Users/franz/Desktop/simulacros_prep/BDD/PUE_AYUN_2024.csv", skiprows = 5, low_memory = False)

data.head()

,CLAVE_CASILLA,CLAVE_ACTA,ID_ENTIDAD,ENTIDAD,ID_MUNICIPIO,MUNICIPIO,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,CODIGO_INTEGRIDAD,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,'210000A0100,'210000A01004,'21,PUEBLA,'001,ACAJETE,'N/A,'N/A,A,'00,...,-,-,-,-,-,-,-,-,-,-
1,'210000A0100,'210000A01004,'21,PUEBLA,'025,AYOTOXCO DE GUERRERO,'N/A,'N/A,A,'00,...,-,-,-,-,-,-,-,-,-,-
2,'210000A0100,'210000A01004,'21,PUEBLA,'030,CAXHUACAN,'N/A,'N/A,A,'00,...,-,-,-,-,-,-,-,-,-,-
3,'210000A0100,'210000A01004,'21,PUEBLA,'036,COXCATLAN,'N/A,'N/A,A,'00,...,-,1,F,ce1ef05319f7a5aa32d9f6a494ec31184465142f35803b...,02/06/2024 23:57:44,02/06/2024 23:58:37,03/06/2024 01:34:24,CATD,ESCANER,ACTA VA
4,'210000A0100,'210000A01004,'21,PUEBLA,'042,CUAUTLANCINGO,'N/A,'N/A,A,'00,...,-,-,-,-,-,-,-,-,-,-

In [3]:
data[data['TOTAL_VOTOS_CALCULADO'] > data['LISTA_NOMINAL']][['MUNICIPIO','TOTAL_VOTOS_CALCULADO','LISTA_NOMINAL']]

                        MUNICIPIO  TOTAL_VOTOS_CALCULADO  LISTA_NOMINAL
13                         PUEBLA                   14.0            4.0
90                   HUAUCHINANGO                   36.0            0.0
178                  HUAUCHINANGO                   64.0            0.0
477                     XICOTEPEC                   66.0            0.0
570                    AHUACATLAN                  854.0          696.0
...                           ...                    ...            ...
7738             TEPANCO DE LOPEZ                  937.0          660.0
7840                      AJALPAN                  162.0            0.0
8056           SAN GABRIEL CHILAC                  890.0          574.0
8130  TLACOTEPEC DE BENITO JUAREZ                   55.0            0.0
8154  TLACOTEPEC DE BENITO JUAREZ                  998.0          567.0

[101 rows x 3 columns]

### Municipios registrados con la inconsistencia

- ATEMPAN

- IZUCAR

- ORIENTAL

- TETELA DE OCAMPO

- TETELES DE AVILA CASTILLO

In [ ]:
data_cand = pd.read_csv("C:/Users/franz/Desktop/PREP/20240603_1540_PREP_PUE/20240603_1540_PREP_AYUN_PUE/PUE_AYUN_Candidaturas_2024.csv")

In [ ]:
data_cand.head()

In [ ]:
sin_nombres_prop = data_cand[(data_cand['CANDIDATURA_PROPIETARIA'] == 'Nombre Apellido Apellido') | (data_cand['CANDIDATURA_SUPLENTE'] == 'Nombre Apellido Apellido')]

sin_nombres_prop = pd.DataFrame(sin_nombres_prop)

In [ ]:
print(sin_nombres_prop)

In [ ]:
sin_nombres_prop.to_csv("inconsistencias_nombres_ayun.csv", index=False)