In [2]:
import numpy as np
import pandas as pd

data = pd.read_csv("C:/Users/Francisco Valerio/Desktop/INE/Simulacros/simulacros_prep/BDD/PUE_GUB_2024.csv", skiprows = 5, low_memory = False)

data.head()

,CLAVE_CASILLA,CLAVE_ACTA,ID_ENTIDAD,ENTIDAD,ID_DISTRITO,DISTRITO,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,CODIGO_INTEGRIDAD,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,'210000M0000,'210000M00002,'21,PUEBLA,'N/A,NaN,'N/A,'N/A,M,'00,...,-,-,-,-,-,-,-,-,-,-
1,'210000A0100,'210000A01002,'21,PUEBLA,'001,XICOTEPEC DE JUAREZ,'N/A,'N/A,A,'00,...,-,1,F,895a47870e3711bef122527544ff95fc239113b84c1e2f...,02/06/2024 23:15:48,02/06/2024 23:17:38,02/06/2024 23:22:36,CATD,ESCANER,ACTA VA
2,'210000A0100,'210000A01002,'21,PUEBLA,'004,ZACAPOAXTLA,'N/A,'N/A,A,'00,...,SIN ACTA POR PAQUETE NO ENTREGADO,0,NaN,NaN,NaN,NaN,NaN,CATD,ESCANER,NaN
3,'210000A0100,'210000A01002,'21,PUEBLA,'006,TEZIUTLAN,'N/A,'N/A,A,'00,...,SIN ACTA POR PAQUETE ENTREGADO SIN BOLSA,0,NaN,NaN,NaN,NaN,NaN,CATD,ESCANER,NaN
4,'210000A0100,'210000A01002,'21,PUEBLA,'007,SAN MARTIN TEXMELUCAN DE LABASTIDA,'N/A,'N/A,A,'00,...,-,1,F,eb54629180ceb640ff16641cccefc04156813a58853304...,02/06/2024 23:38:35,02/06/2024 23:41:44,03/06/2024 01:21:22,CATD,ESCANER,ACTA VA

In [8]:
columnas = ['ID_DISTRITO','DISTRITO','CODIGO_INTEGRIDAD', 'OBSERVACIONES', 'FECHA_HORA_ACOPIO', 'CONTABILIZADA']

nas = data[data['ID_DISTRITO'].isna()]

registros_filtrados = nas[columnas]

print(registros_filtrados)

     ID_DISTRITO DISTRITO                                  CODIGO_INTEGRIDAD  \
8334         NaN      NaN  5141428d0fcea7ebda1e88f7b0bf919398f372b8bc9e7e...
8335         NaN      NaN  2aea8cf372d6dbaba19110413e7275f319146a1dc23964...
8336         NaN      NaN  73070248482d26bb4732709e5654e9a8d14bc77c392df6...
8337         NaN      NaN  95d80a00ecc1518d9146970d50632031fdb316a4795c4c...
8338         NaN      NaN  5c8512c909b5d81b536157d2018a5f95d46dc424b380c5...
8339         NaN      NaN  bea327d7d500920fa7b0d3c378c9a76648f2f927c6fecd...
8340         NaN      NaN  4fb375c335bf9c4f55a49066f3b9618bf0b0bb60df26a5...
8341         NaN      NaN  24aa92ce3ff0854c8fa399d6df9d49752d80ee104c45ae...
8342         NaN      NaN  a934581a14943cc3d79a12c24096f5c77281e2a1ffeea5...
8343         NaN      NaN  a865efbbc7a4e1843f1fd8bea36efce1188f1783dd36c3...
8344         NaN      NaN  08d4985325ba5210792960eb1a0e0a586436493f5163e3...
8345         NaN      NaN  121881580f067493a83e20ed52549eb93c93d838203ab3...

          OBSERVACIONES    FECHA_HORA_ACOPIO CONTABILIZADA
8334  FUERA DE CATALOGO  02/06/2024 22:56:24             2
8335  FUERA DE CATALOGO  02/06/2024 23:48:53             2
8336  FUERA DE CATALOGO  02/06/2024 23:52:14             2
8337  FUERA DE CATALOGO  03/06/2024 00:21:24             2
8338  FUERA DE CATALOGO  03/06/2024 01:07:07             2
8339  FUERA DE CATALOGO  03/06/2024 01:11:56             2
8340  FUERA DE CATALOGO  03/06/2024 01:24:23             2
8341  FUERA DE CATALOGO  03/06/2024 01:51:06             2
8342  FUERA DE CATALOGO  03/06/2024 01:51:37             2
8343  FUERA DE CATALOGO  03/06/2024 01:51:57             2
8344  FUERA DE CATALOGO  03/06/2024 02:35:15             2
8345  FUERA DE CATALOGO  03/06/2024 03:03:40             2

In [3]:
data[data['TOTAL_VOTOS_CALCULADO'] > data['LISTA_NOMINAL']][['MUNICIPIO','TOTAL_VOTOS_CALCULADO','LISTA_NOMINAL']]

                        MUNICIPIO  TOTAL_VOTOS_CALCULADO  LISTA_NOMINAL
13                         PUEBLA                   14.0            4.0
90                   HUAUCHINANGO                   36.0            0.0
178                  HUAUCHINANGO                   64.0            0.0
477                     XICOTEPEC                   66.0            0.0
570                    AHUACATLAN                  854.0          696.0
...                           ...                    ...            ...
7738             TEPANCO DE LOPEZ                  937.0          660.0
7840                      AJALPAN                  162.0            0.0
8056           SAN GABRIEL CHILAC                  890.0          574.0
8130  TLACOTEPEC DE BENITO JUAREZ                   55.0            0.0
8154  TLACOTEPEC DE BENITO JUAREZ                  998.0          567.0

[101 rows x 3 columns]

### Municipios registrados con la inconsistencia

- ATEMPAN

- IZUCAR

- ORIENTAL

- TETELA DE OCAMPO

- TETELES DE AVILA CASTILLO

In [ ]:
data_cand = pd.read_csv("C:/Users/franz/Desktop/PREP/20240603_1540_PREP_PUE/20240603_1540_PREP_AYUN_PUE/PUE_AYUN_Candidaturas_2024.csv")

In [ ]:
data_cand.head()

In [ ]:
sin_nombres_prop = data_cand[(data_cand['CANDIDATURA_PROPIETARIA'] == 'Nombre Apellido Apellido') | (data_cand['CANDIDATURA_SUPLENTE'] == 'Nombre Apellido Apellido')]

sin_nombres_prop = pd.DataFrame(sin_nombres_prop)

In [ ]:
print(sin_nombres_prop)

In [ ]:
sin_nombres_prop.to_csv("inconsistencias_nombres_ayun.csv", index=False)